# Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions 
# and other software and tools, and its AMPP partner logic 
# functions, and any output files from any of the foregoing 
# (including device programming or simulation files), and any 
# associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License 
# Subscription Agreement, the Altera Quartus Prime License Agreement,
# the Altera MegaCore Function License Agreement, or other 
# applicable license agreement, including, without limitation, 
# that your use is for the sole purpose of programming logic 
# devices manufactured by Altera and sold by Altera or its 
# authorized distributors.  Please refer to the applicable 
# agreement for further details.


# ***************************************************************************
# ***************************************************************************
# 
# File:		C:/BA/Software_projects/FPGA/1533_FPGA/BA_1533_TX/simulation/modelsim/BA1533_TX_dump_all_vcd_nodes.tcl
# 
# Description:	Script for ModelSim-Altera (Verilog) VCD File Dumping
# 		This script is used to direct ModelSim-Altera (Verilog) to dump
# 		all nodes in the design to a VCD output file
# 
# Usages:	C:/BA/Software_projects/FPGA/1533_FPGA/BA_1533_TX/simulation/modelsim/BA1533_TX_dump_all_vcd_nodes.tcl
# 
# Generated by:	Quartus Prime
# 		Version 15.1.0 Build 185 10/21/2015 SJ Lite Edition
# 
# Date:		Wed Jul 04 17:49:07 2018
# 
# Design:	BA1533_TX
# 
# ***************************************************************************
# ***************************************************************************

# ----------------------------------------------------------------
#
proc add_vcd_signals { hierarchy vcd_filename } {
#
# Description:	This function directs ModelSim-Altera (Verilog) to print out the
#		appropriate VCD signals, with the hierarchy level
#		prepended to each signal name
#
# ----------------------------------------------------------------

   catch { vcd add "$hierarchy/tx_pll_c_aaltpll_component_aauto_generated_awire_pll1_fbout" }
   catch { vcd add "$hierarchy/tx_pll_c_aaltpll_component_aauto_generated_awire_pll1_clk\[0\]" }
   catch { vcd add "$hierarchy/tx_pll_c_aaltpll_component_aauto_generated_awire_pll1_clk\[1\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[27\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[28\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[29\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[30\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[24\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[25\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[19\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[20\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[10\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[11\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[12\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[13\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[14\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[16\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[17\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[15\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[18\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[21\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[22\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[23\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[26\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[31\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[9\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[8\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[7\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[6\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[5\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[4\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[3\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[2\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[1\]" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a1_a_a31_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a1_a_a32" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a2_a_a33_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a2_a_a34" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a3_a_a35_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a3_a_a36" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a4_a_a37_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a4_a_a38" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a5_a_a39_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a5_a_a40" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a6_a_a41_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a6_a_a42" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a7_a_a43_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a7_a_a44" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a8_a_a45_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a8_a_a46" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a9_a_a47_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a9_a_a48" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a10_a_a49_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a10_a_a50" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a11_a_a51_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a11_a_a52" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a12_a_a53_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a12_a_a54" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a13_a_a55_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a13_a_a56" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a14_a_a57_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a14_a_a58" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a15_a_a59_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a15_a_a60" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a16_a_a61_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a16_a_a62" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a17_a_a63_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a17_a_a64" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a18_a_a65_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a18_a_a66" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a19_a_a67_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a19_a_a68" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a20_a_a69_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a20_a_a70" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a21_a_a71_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a21_a_a72" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a22_a_a73_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a22_a_a74" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a23_a_a75_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a23_a_a76" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a24_a_a77_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a24_a_a78" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a25_a_a79_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a25_a_a80" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a26_a_a81_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a26_a_a82" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a27_a_a83_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a27_a_a84" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a28_a_a85_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a28_a_a86" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a29_a_a87_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a29_a_a88" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a30_a_a89_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a30_a_a90" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a31_a_a91_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aFIFOram_aq_b\[0\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aFIFOram_aq_b\[7\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aFIFOram_aq_b\[6\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aFIFOram_aq_b\[5\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aFIFOram_aq_b\[4\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aFIFOram_aq_b\[3\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aFIFOram_aq_b\[2\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aFIFOram_aq_b\[1\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter\[1\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter\[2\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter\[0\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter\[3\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter\[5\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter\[4\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter\[6\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter\[7\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a0_a_a8_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a0_a_a9" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a1_a_a10_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a1_a_a11" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a2_a_a13_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a2_a_a14" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a3_a_a15_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a3_a_a16" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a4_a_a17_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a4_a_a18" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a5_a_a19_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a5_a_a20" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a6_a_a21_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a6_a_a22" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a7_a_a23_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_comb_bita0_acombout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_comb_bita0_aCOUT" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_comb_bita1_acombout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_comb_bita1_aCOUT" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_comb_bita2_acombout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_comb_bita2_aCOUT" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_comb_bita3_acombout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_comb_bita3_aCOUT" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_comb_bita4_acombout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_comb_bita4_aCOUT" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_comb_bita5_acombout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_comb_bita0_acombout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_comb_bita0_aCOUT" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_comb_bita1_acombout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_comb_bita1_aCOUT" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_comb_bita2_acombout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_comb_bita2_aCOUT" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_comb_bita3_acombout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_comb_bita3_aCOUT" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_comb_bita4_acombout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_comb_bita4_aCOUT" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_comb_bita5_acombout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_comb_bita5_aCOUT" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_comb_bita6_acombout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aserial_data_out_aq" }
   catch { vcd add "$hierarchy/tx_c_amax_tx_flag_aq" }
   catch { vcd add "$hierarchy/tx_c_atx_bit_data_aq" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg\[0\]" }
   catch { vcd add "$hierarchy/tx_c_aLessThan0_a0_combout" }
   catch { vcd add "$hierarchy/tx_c_aLessThan0_a1_combout" }
   catch { vcd add "$hierarchy/tx_c_aLessThan0_a2_combout" }
   catch { vcd add "$hierarchy/tx_c_aLessThan0_a3_combout" }
   catch { vcd add "$hierarchy/tx_c_aLessThan0_a4_combout" }
   catch { vcd add "$hierarchy/tx_c_aLessThan0_a5_combout" }
   catch { vcd add "$hierarchy/tx_c_aLessThan0_a6_combout" }
   catch { vcd add "$hierarchy/tx_c_aLessThan0_a7_combout" }
   catch { vcd add "$hierarchy/tx_c_aLessThan0_a8_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_bit_data_a0_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg\[1\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_atransmitting_data_aq" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_aall_bits_transmitted_aq" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aempty_dff_aq" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg_a0_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_clock_rising_edge_aq" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg_a1_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count\[0\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg\[2\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aread_fifo_en_a0_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg_a2_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_atransmitting_data_a0_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abit_counter\[2\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abit_counter\[0\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abit_counter\[1\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abit_counter\[3\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_aEqual2_a0_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_is_1_dff_aq" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_aEqual0_a0_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_aEqual0_a1_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_aEqual0_a2_combout" }
   catch { vcd add "$hierarchy/tx_c_atx_count_a0_a_a93_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_alow_addressa\[0\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_lsb_aq" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aram_read_address_a0_a_a0_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_reg_bit\[0\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_alow_addressa\[1\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aram_read_address_a1_a_a1_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_reg_bit\[1\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_alow_addressa\[2\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aram_read_address_a2_a_a2_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_reg_bit\[2\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_alow_addressa\[3\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aram_read_address_a3_a_a3_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_reg_bit\[3\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_alow_addressa\[4\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aram_read_address_a4_a_a4_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_reg_bit\[4\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_alow_addressa\[5\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aram_read_address_a5_a_a5_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_msb_acounter_reg_bit\[5\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_alow_addressa\[6\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aram_read_address_a6_a_a6_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg\[3\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg_a3_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abit_counter_a2_a_a4_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_aAdd1_a0_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abit_counter_a2_a_a5_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abit_counter_a1_a_a6_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_aAdd1_a1_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abit_counter_a3_a_a7_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_is_2_dff_aq" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_counter_a0_a_a12_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_a__a0_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg\[4\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg_a4_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_reg_bit\[6\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_reg_bit\[5\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_reg_bit\[4\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_reg_bit\[3\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_athree_comparison_aaneb_result_wire_a0_a_a0_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_reg_bit\[2\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_reg_bit\[1\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ausedw_counter_acounter_reg_bit\[0\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_athree_comparison_aaneb_result_wire\[0\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg\[5\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg_a5_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg\[6\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg_a6_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg\[7\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg_a7_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg\[8\]" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg_a8_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_adata_out_shift_reg_a9_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abit_counter_a0_a_a8_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_aempty_dff_a0_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_FIFO_aSync_FIFO_aauto_generated_adpfifo_ard_ptr_lsb_a0_combout" }
   catch { vcd add "$hierarchy/a_aGND_acombout" }
   catch { vcd add "$hierarchy/UART_TXD" }
   catch { vcd add "$hierarchy/UART_TXD" }
   catch { vcd add "$hierarchy/led1" }
   catch { vcd add "$hierarchy/led1" }
   catch { vcd add "$hierarchy/led2" }
   catch { vcd add "$hierarchy/led2" }
   catch { vcd add "$hierarchy/led3" }
   catch { vcd add "$hierarchy/led3" }
   catch { vcd add "$hierarchy/led4" }
   catch { vcd add "$hierarchy/led4" }
   catch { vcd add "$hierarchy/tx_bit_data" }
   catch { vcd add "$hierarchy/tx_bit_data" }
   catch { vcd add "$hierarchy/UART_RXD" }
   catch { vcd add "$hierarchy/clk_ainput_o" }
   catch { vcd add "$hierarchy/clk" }
   catch { vcd add "$hierarchy/tx_pll_c_aaltpll_component_aauto_generated_awire_pll1_clk_a1_a_aclkctrl_outclk" }
   catch { vcd add "$hierarchy/tx_pll_c_aaltpll_component_aauto_generated_awire_pll1_clk_a0_a_aclkctrl_outclk" }
   catch { vcd add "$hierarchy/clk_ainputclkctrl_outclk" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_aall_bits_transmitted_afeeder_combout" }
   catch { vcd add "$hierarchy/uart_mcu_c_ars232_0_aRS232_Out_Serializer_aRS232_Out_Counters_abaud_clock_rising_edge_afeeder_combout" }
}

# ----------------------------------------------------------------
#
proc main { argv } {
#
# Description:	Main entry point to script.  Iterate over all
#		hierarchy levels specified, and direct ModelSim-Altera (Verilog)
#		to print the relevant signals under each level
#
# ----------------------------------------------------------------

   set vcd_filename "BA1533_TX.vcd"
   set hierarchy "DUT"

   vcd file "$vcd_filename"
   vcd on

   add_vcd_signals $hierarchy $vcd_filename
}

main $argv
